name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      EMULATOR_API_LEVEL: 30
      ANDROID_BUILD_TOOLS_VERSION: 30.0.3
      EMULATOR_NAME: test
      AVD_CONFIG: "hw.lcd.height=1280 hw.lcd.width=720 hw.device.name=Pixel_3a_API_30"
      APK_PATH: "app/build/outputs/apk/debug/app-debug.apk"

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Install Android Build Tools
        run: echo y | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION"
      - name: Install Android Emulator
        run: echo y | sdkmanager "emulator"
      - name: Create Android Emulator
        run: echo no | avdmanager create avd --force --name=$EMULATOR_NAME --package='system-images;android-$EMULATOR_API_LEVEL;default;x86_64' --abi='default/x86_64' --device=$AVD_CONFIG
      - name: Launch Android Emulator
        run: |
          emulator -avd $EMULATOR_NAME -no-audio -no-window -no-boot-anim -accel on -wipe-data &
          android-wait-for-emulator
          adb shell input keyevent 82 &
      - name: Build and Run Tests on Emulator
        run: |
          ./gradlew clean
          ./gradlew assembleDebug
          ./gradlew assembleAndroidTest
          ./gradlew createDebugCoverageReport
          run: ./gradlew clean createDebugCoverageReport sonarqube
