name: Run instrumentation tests and generate coverage report
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew
    - name: Run instrumentation tests and generate coverage report
      run: ./gradlew clean createDebugCoverageReport sonarqube
